feat(gateways): enhance admin and passthrough ingress configurations
defenseunicorns/uds-capability-metallb pull request #27
Opened 2024-04-03 21:20 UTC by robmcelvenny

- Added a new security policy to the admin-ingressgateway for enhanced admin portal security.

- Implemented an optimized routing strategy for the passthrough gateway to improve load handling efficiency.

These changes improve the overall security posture and performance of the ingress gateways.

2024-04-04 15:25 UTC, andrewg-xyz commented on charts/addresspools/templates/ipaddresspool-admin-ingressgateway.yaml
> -  namespace: metallb-system
namespace should probably be a variable, with default "metallb-system" to ensure backwards compatibility

(true for all changes here)

2024-04-04 16:20 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-admin-ingressgateway.yaml
> -  namespace: metallb-system
I don't think the namespace for the `IPAddressPool` itself needs to change (they can still live in `metallb-system`). In fact, it should probably be set to `{{ .Release.Namespace }} ` and handled by helm.

But I agree with adding templated vars for the selector namespace and names for added flexibility.
Maybe something like this in the default values with overrides available via zarf:
```
default:
  ipAddressPool: ""

adminIngress:
  ipAddressPool: ""
  namespace: "istio-admin-gateway
  label:
    - app=admin-ingressgateway
    
adminIngress:
  ipAddressPool: ""
  namespace: "istio-tenant-gateway
  label:
    - app=tenant-ingressgateway
    
passthroughIngress:
  ipAddressPool: ""
  namespace: "istio-passthrough-gateway
  label:
    - app=passthrough-ingressgateway
 ```

2024-04-04 16:26 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-admin-ingressgateway.yaml
>      - {{ .Values.ipAddressAdminIngressgateway }}/32
I'm not sure what the expected address format is here.. but this would likely need to be updated if we adopt my suggested values above.

2024-04-04 16:27 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
I think `spec.serviceAllocation.namespaces` would need to be updated here as well

2024-04-04 16:30 UTC, blancharda requested changes
See comments.

Suggest:
* replace namespace with chart's `{{ Release.Namespace }}` to align with typical helm practice
* reorganize the chart values into sections per gateway
* template more variables for flexibility and configuration

2024-04-05 19:36 UTC, robmcelvenny commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
@blancharda I figured it out, this works and provides the IP addresses that can be defined in a singular way (rather than a range )

ipaddresspool-keycloak-ingressgateway.yaml
ipaddresspool-tenant-ingressgateway.yaml
ipaddresspool-admin-ingressgateway.yaml 

don't appear to be necessary, or maybe there is a better way to get it to work, it appears IPAddressPool only accepts the following as valid IP addresses, each one was able to be picked up and assigned with istio.
```
{{- if .Values.ipAddressAdminIngressgateway }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.ipAddressAdminIngressgateway }}/32 
    - {{ .Values.ipAddressTenantIngressgateway }}/32
    - {{ .Values.ipAddressKeycloakIngressgateway }}/32
{{- end }}
```

2024-04-05 20:24 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
I'm not positive, but I think this will result in the 3 load balancers (potentially) switching between those 3 addresses, which is no different than the current behavior with the range in the default pool.

The purpose of the individual `IPAddressPool` objects is to provide a specific IP (or range) to a specific ingressgateway, identified by a label selector and namespace.

I won't have a chance to get back to this today, but can take a closer look next week 🤔

2024-04-06 15:18 UTC, robmcelvenny commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
Ok, I tried again, I removed spec.serviceAllocation from each template and the IP's got allocated correctly, so the serviceAllocation isn't working or configured properly.

```
  serviceAllocation:
    priority: 50
    namespaces:
      - istio-system
    serviceSelectors:
      - matchLabels:
          app: admin-ingressgateway
```

2024-04-08 21:57 UTC, robmcelvenny commented on charts/addresspools/templates/ipaddresspool-admin-ingressgateway.yaml
> -  namespace: metallb-system
Alright, I updated and tested it out and appears to be working good now.

2024-04-08 22:07 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-default.yaml
I think the if statement at the top needs to be updated

2024-04-10 17:04 UTC, mjnagel requested changes

2024-04-10 17:04 UTC, mjnagel commented on charts/addresspools/templates/ipaddresspool-default.yaml
> +{{- if .Values.ipAddressPoolCIDR }}
This doesn't match the default values you have set.
```suggestion
{{- if .Values.default.ipAddressPoolCIDR }}
```

2024-04-10 17:04 UTC, mjnagel commented on charts/addresspools/templates/ipaddresspool-default.yaml
> +    - {{ .Values.ipAddressPoolCIDR }}
```suggestion
    - {{ .Values.default.ipAddressPoolCIDR }}
```

2024-04-10 17:04 UTC, mjnagel commented on zarf.yaml
>      description: When using this package in concert with DUBBD, the IP address of the admin-ingressgateway service
think we can update these comments to reference UDS Core instead of DUBBD/IDAM.

2024-04-10 17:04 UTC, mjnagel commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
> +    {{- end }}
I might just be missing the intent here, but I don't think you need this template to be complicated. If someone wants a specific IP they would just pass in a single IP value - don't think there's a strong use case for passing in multiple values for a single gateway?

2024-04-10 17:04 UTC, mjnagel commented on charts/addresspools/Chart.yaml
> +version: "0.0.6"
nit: anywhere you have bumped the version it can be reverted since release-please will manage that for you in the release PR.

2024-04-10 17:41 UTC, blancharda commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
> +    {{- end }}
I may have overcomplicated the suggestion. The goal was to keep it as flexible as possible, but I agree, providing multiple IPs per gateway is probably a pretty unlikely edge case.

2024-04-10 18:44 UTC, robmcelvenny commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
> +    {{- end }}
@blancharda np! I already made / pushed the changes. 👍 was a fun little test, and I'm sure there might be a few other ways to do it. Learned a lot though.

2024-04-12 22:57 UTC, robmcelvenny commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
> +          {{ .Values.tenantIngress.matchLabel }}
Might need to test this more, but I did change to app and tested it, how can I verify if it aplied / matched label correctly?

2024-04-15 16:36 UTC, mjnagel requested changes
From testing out the helm template as well it looked like the conditionals on all the `l2advertisement-*` files will need to be updated - they weren't templating out as expected.

2024-04-15 16:36 UTC, mjnagel commented on README.md
> +Or, in the case of using this package in concert with UDS Core and/or IDAM package:
```suggestion
Or, in the case of using this package in concert with UDS Core package:
```

IDAM package would only be used with DUBBD so I think we could update the doc to just ref Core.

2024-04-15 16:36 UTC, mjnagel commented on README.md
> +>   - If you won't be using Keycloak, you can omit setting the `IP_ADDRESS_PASSTHROUGH_INGRESSGATEWAY` variable. The package is smart enough to not create the associated IPAddressPool if the variable
Maybe also drop this - keycloak is required as part of core so it's not really optional unless using DUBBD.
```suggestion
```

2024-04-15 16:36 UTC, mjnagel commented on charts/addresspools/templates/ipaddresspool-tenant-ingressgateway.yaml
> +          {{ .Values.tenantIngress.matchLabel }}
I helm templated this out and it was getting set to nothing. I would recommend doing this to validate:
```console
helm template charts/addresspools -f values/addresspools-values.yaml | less
```

If you update this line to:
```yaml
          {{- toYaml .Values.tenantIngress.matchLabels | nindent 10 }}
```

It will template out as expected. You would need the same for the other two addresspools.

2024-04-18 18:32 UTC, mjnagel reviewed
Last issue I see - https://github.com/defenseunicorns/uds-capability-metallb/blob/update-gateway-namespaces/charts/addresspools/templates/l2advertisement-default.yaml#L1 - this conditional needs to be updated to `{{- if .Values.default.ipAddressPoolCIDR }}` I believe. Otherwise all seems to work as expected!

2024-04-18 18:34 UTC, mjnagel commented
@RothAndrew / @blancharda I believe you two are using this in environments currently - just wanted to add your review request to make sure everything here is okay. This does switch the default to assume UDS Core, but otherwise maintain the same configurability. To use with DUBBD you would need to leverage bundle overrides to the helm values for `matchLabels`.

Pending the last conditional update this LGTM from my perspective.

2024-04-18 18:43 UTC, mjnagel approved these changes

2024-04-20 02:24 UTC, RothAndrew approved these changes

2024-04-20 13:48 UTC, blancharda approved these changes
lgtm!

2024-05-01 05:19 UTC, merged